/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmgameboy_free: (a: number, b: number) => void;
export const button_a: () => number;
export const button_b: () => number;
export const button_down: () => number;
export const button_left: () => number;
export const button_right: () => number;
export const button_select: () => number;
export const button_start: () => number;
export const button_up: () => number;
export const wasmgameboy_audio_sample_rate: (a: number) => number;
export const wasmgameboy_clear_audio_buffer: (a: number) => void;
export const wasmgameboy_frame_count: (a: number) => bigint;
export const wasmgameboy_game_title: (a: number) => [number, number];
export const wasmgameboy_get_audio_buffer: (a: number) => [number, number];
export const wasmgameboy_get_framebuffer: (a: number) => [number, number];
export const wasmgameboy_is_cgb_game: (a: number) => number;
export const wasmgameboy_load_sram: (a: number, b: number, c: number) => [number, number];
export const wasmgameboy_load_state: (a: number, b: number, c: number) => [number, number];
export const wasmgameboy_new: (a: number, b: number) => [number, number, number];
export const wasmgameboy_press_button: (a: number, b: number) => void;
export const wasmgameboy_release_button: (a: number, b: number) => void;
export const wasmgameboy_reset: (a: number) => void;
export const wasmgameboy_run_cycles: (a: number, b: number) => void;
export const wasmgameboy_run_frame: (a: number) => number;
export const wasmgameboy_save_sram: (a: number) => [number, number];
export const wasmgameboy_save_state: (a: number) => [number, number];
export const wasmgameboy_screen_height: (a: number) => number;
export const wasmgameboy_screen_width: (a: number) => number;
export const wasmgameboy_total_cycles: (a: number) => bigint;
export const init: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
